DaftBrit/NoitaArchipelago

settings.lua

Previously did not support all supported characters for URLs and slot names.

Make settings more permissive

---

data/archipelago/scripts/item_utils.lua
init.lua

-Items get sent properly in async.
-Potions and traps are not sent in async.
-All items are re-sent on new game, except for traps and potions.
I ended up removing the ShouldDeliverItem line from RECV_MSG.ReceivedItems because I couldn't figure out a good way to fit it in properly, and I don't really understand it still. But it seems to be working without it?
Added an is_redeliverable_item table to item_utils. Purpose is to just clearly define whether an item should be redelivered. There was discussion before on whether respawns should be redelivered, so feel free to change that to false. Maybe we'll make it an option later.

Made item redelivery function properly

---

data/archipelago/scripts/ap_spawned_timer_finish.lua
data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/item_mappings.lua
data/archipelago/scripts/item_utils.lua
init.lua

Made it so items spawn around you on new game. This isn't the final design intent, as currently there are issues, such as gourds just falling to the ground and activating, and also this is sloppy. Ideally the end result will be a box or something the player can interact with, or bins that fill up with items. Something like that.
Also added another category to item_mapping, newgame, which defines which items should be re-sent on new game.

Item Delivery on Spawn

---

init.lua

Making it longer to let worse connections or worse computers use it properly

Quick fix for the spawned timer

---

README.md

There's some things, such as potion redelivery being disabled on spawn and gold not getting redelivered, that may look like bugs or issues. This section is to explain that they are intentional design choices, so that people don't submit bug reports for things that aren't bugs, and to give a little more insight as to how the world is laid out.
For the design intent section, I figured it would make sense to contextualize why Noita works well in Archipelago.

Added Design Intent and Notes and Quirks section

---

data/archipelago/scripts/ap_pedestal_replacer.lua
data/archipelago/scripts/ap_utils.lua

Gave pedestal items name and description in the event that they don't properly get them (in the event that your datapackage isn't there, or if it wasn't there fast enough). Kind of want to make them spawn normally if the datapackage didn't show up, but I feel like we'll end up missing bug reports if we do.
Also didn't realize that renaming a branch would close the pull request. Somewhat expected it, but github didn't give a warning message or anything so whatever.

Pedestal crash avoidance

---

data/archipelago/scripts/patches/extend_temple_altar.lua

Fixes the shop item prices. Just tested each shop, and the prices match the range of prices that wands typically sell for now. For the secret shop, it matches the typical Hiisi Base wand prices.

Shop prices fixed to match vanilla game wand shop prices

---

data/archipelago/scripts/ap_utils.lua

Added in a missing Log dofile. Was flooding the log with errors when starting up the game while one of the cache files was open.

Missing Log reference

---

data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/item_utils.lua
data/archipelago/scripts/patches/ap_orb_init_random.lua
data/archipelago/scripts/patches/ap_orb_pickup_random.lua
init.lua

Before, even with the offset, the flaw was that there was still the same seed for the random offset, so it just offset them all to the same exact spot. Now we check a global value, spawn the item/trap, then increment it. I have tested and it does appear to be working.
And while the random spawn position offset is no longer required, I think it looks visually better with it.

Make it so if multiple items spawn, they don't spawn with the same seed

---

data/archipelago/scripts/patches/ap_orb_init_random.lua
data/archipelago/scripts/patches/ap_orb_pickup_random.lua

This is to fix an issue where if you pick up a natural-spawn orb that has a check, it won't actually show the check message because of the orb's message and the heart pickup message. And it doesn't increase your orb count anyway, so the message doesn't matter much.
Also got rid of the kolmi shout since it doesn't increase kolmi's health either.

Removed orb message for natural-spawn orbs

---

data/archipelago/scripts/patches/ap_pedestal_replacer.lua

Now they'll spawn vanilla if an error occurs, and log a print message.

Fix for pedestals

---

data/archipelago/materials.xml
data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/items/potion_saver_remover.lua
data/archipelago/scripts/patches/ap_pedestal_replacer.lua
init.lua

So there's an iframe line in the damage model component.
It doesn't prevent physics damage, and the potion doesn't update it's material component until it has been picked up and dropped again after the material component is changed, so it can still be destroyed by physics-modifying attacks, but it's less likely to be destroyed since you now have to destroy the entire model during those first 90 frames of life instead of just 51% of it.
Also, you can send items directly using the server console. When you do so, it sends with a location ID of -1. I've added in some support for this since, without the additional support, it only sends the first time you run the command. Any other time, it sees that you've already sent an item from location -1, so it doesn't send it again since it thinks it's …

Potions are safer, also better support for ap console /send

---

data/archipelago/entities/items/base_ap_shopitem.xml
data/archipelago/entities/items/pickup/ap_chest_random.xml
data/archipelago/materials.xml
data/archipelago/scripts/patches/ap_pedestal_replacer.lua
data/archipelago/scripts/patches/extend_forge_item_convert.lua

Also fixed a duplicate material color definition, as the gorilla glass and ap chest had the same color (woops)

Item radar works on pedestal items now

---

data/archipelago/scripts/ap_utils.lua
init.lua

If player holds the right key during the intro logos, they'll count as moving right before items spawn in the starting cave, making them not spawn on new game.
Fixed by making it so instead of checking whether the player has moved right, we're checking if they've walked a good distance into the cave.
The only edge case I can think of here is if the player's internet is so goddamn bad that they can be playing for long enough that they can get into the cave before they receive their items message. In which case, the advice there would be to wait at the entrance for your items to spawn before continuing.

Fix for items not spawning in starting cave sometimes (hopefully)

---

data/archipelago/scripts/ap_orb_init_randomizer_spawned.lua
data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/constants.lua
data/archipelago/scripts/first_connect_flag_remover.lua
data/archipelago/scripts/item_mappings.lua
data/archipelago/scripts/item_utils.lua
data/archipelago/scripts/items/ap_chest_random.lua
data/archipelago/scripts/items/ap_pedestal_processed.lua
data/archipelago/scripts/patches/ap_pedestal_replacer.lua
data/archipelago/scripts/shopitem_processed.lua
data/archipelago/scripts/shopitem_utils.lua
init.lua

Slot co-op now works as expected. If someone picks up an item and that item is on a pedestal or in the shop, it should be delivered to the other person playing, and remove that item from the world for that player. I didn't test this part yet as it is hard to test solo, but at the very least it didn't seem to impact anything while playing without slot co-op.
Also fixed the items spawning weirdly on first connection. I tested this a few times with different set ups, and tested it in the RC5 Async. It worked every time -- gave you your normal item spawns in the starting cave and gave you your gold and extra lives that were sent before you connected (since it would be dumb if you didn't get them on your very first spawn into the session).

Slot co-op and fixes to spawning items on first connection

---

data/archipelago/entities/items/orbs/vanilla_orb.xml
data/archipelago/scripts/ap_orb_init_randomizer_spawned.lua
init.lua
settings.lua

Only affects the orbs that are spawned by the randomizer, meaning just the orbs that actually increase your orb counter while you have the mod enabled.

Added option to change what art shows up on the randomizer-spawned orbs

---

data/archipelago/entities/items/orbs/ap_orb_base_randomizer_spawned.xml
data/archipelago/entities/items/orbs/ap_orb_randomizer_spawned.xml
data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/patches/ap_pedestal_replacer.lua
data/archipelago/scripts/shopitem_utils.lua

The orb issue was the CameraBoundComponent existing (it's on orbs themselves for some reason).
The slot co-op trap issue was that we weren't adding the my_ap_item tag to traps in the shop.
Draft PR until I've tested it

Fixed orbs and slot co-op issue

---

data/archipelago/scripts/apply_ap_patches.lua
data/archipelago/scripts/items/pedestal_trap_pickup.lua
data/archipelago/scripts/patches/ap_heart_and_chest_replacer.lua
data/archipelago/scripts/patches/ap_pedestal_replacer.lua
data/archipelago/scripts/shopitem_processed.lua

Pedestal replacer now replaces trap puzzles in the mines, as this is the only place with this type of pedestal.
Chest/heart replacer now replaces chests that get spawned with a different script in the Mines and the Tower. It only sometimes replaces them in the mines though due to that timing issue where, if the pedestal spawns before you can do your location scout stuff, they'll spawn vanilla.
Also went in and cleaned up a thing that was giving error messages. The particle effects for your own ap item on chests and the stealable quality of shop items were throwing it. As a result, this also makes shop items stealable as intended.

Updated chest and pedestal replacers

---

init.lua

Currently, when you connect to the game on an unsecure connection, the player first sees a TLS error, then that something related to TLS failed, and then a successful connection.
This has led to a bug report about an actual connection issue being misconstrued as being related to this, making information gathering harder to actually diagnose the issue. So, changing around how these messages are shown to stop that issue from happening.
Also, made it so if you specifically put in wss:// or https://, it'll use that instead of falling back to unsecure. That way, if you're specifically trying to get a secure connection, you don't fall back to an unsecure connection.

Changed connection error messaging

---

init.lua

There's a trailing garbage message that's been showing up recently. No clue why it's showing up -- I don't think AP is sending it for a keep alive, and I don't know enough to say whether pollnet is doing it.
But, it's making a scary error message on-screen for players, and that sucks, so I'm limiting that message to just show up in logs instead.

Suppress trailing garbage message

---

data/archipelago/entities/items/orbs/ap_orb_base_randomizer_spawned.xml
data/archipelago/scripts/ap_orb_pickup_randomizer_spawned.lua
init.lua

The issue was that if there were more orbs on the ground than you need to achieve your goal, the existing orbs would still have valid OrbComponents, and so would still increment your orb counter. Now, they get removed when you pick them up, stopping the counter from incrementing.

Fix issue where you sometimes go over your orb goal amount

---

init.lua
settings.lua

The client tags will now update when the death link setting is toggled

Make death link tags properly update

---

init.lua

```
LUA: 17:38:29 [AP] No connection could be made because the target machine actively refused it.    
Lua error - [string "mods/archipelago/init.lua"]:73: attempt to index upvalue 'slot_options' (a nil value)
Stack traceback:
[string "mods/archipelago/init.lua"]:73: in function 'IsDeathLinkEnabled'
[string "mods/archipelago/init.lua"]:574: in function <[string "mods/archipelago/init.lua"]:570>
```
Attempting to fix this with this PR.
When the player connected to their slot, it immediately disconnected them. I'm going to assume OnPauseChanged can happen at the main menu somewhere? Will test this tonight, just writing it up in browser on my work computer for now.

Death link fix
