DaftBrit/NoitaArchipelago

init.lua

Eliminates the mega-function, makes things easier to read/follow.

Major init.lua refactor

---

init.lua

When players are polymorphed the player entity is removed, this resolves that issue and is also what badtimes.lua does.

Remove global_player

---

init.lua

I barely know what I'm doing, but this worked without breaking things as far as I can tell.
Specific perks can now spawn in the randomizer pool. The intent is for them to carry over between lives, but that functionality is not in here yet.

Added perk spawning and a couple notes

---

data/archipelago/scripts/extend_temple_altar.lua
data/archipelago/scripts/shopitem_processed.lua
init.lua

- Fix not being able to collect your own wands from shops
- Fix receiving duplicates of your own items from shops
- PrintJSON now writes text correctly as AP expects it
- PrintJSON no longer spawns items, that's in ReceivedItems
- Implement ConnectionRefused
- ReceivedItems will resend everything at the start but a solution for it is being worked on

Rewrite PrintJSON, fix two shop issues

---

data/archipelago/scripts/item_utils.lua
init.lua

- Also use proper badtimes strings
- Move checklist retrieval outside of message processing

Transfer slot options more easily from server

---

data/archipelago/lib/global_complex.lua
data/archipelago/scripts/extend_temple_altar.lua
data/archipelago/scripts/globals.lua
data/archipelago/scripts/item_utils.lua
data/archipelago/scripts/shopitem_processed.lua
init.lua

Depends on https://github.com/DaftBrit/NoitaArchipelago/pull/23

Fix AP items respawning in shops

---

data/archipelago/lib/cache_manager.lua
data/archipelago/scripts/apply_ap_patches.lua
data/archipelago/scripts/constants.lua
data/archipelago/scripts/extend_snowcastle_cavern.lua
data/archipelago/scripts/extend_temple_altar.lua
data/archipelago/scripts/shopitem_processed.lua
data/archipelago/scripts/shopitem_utils.lua
init.lua

Note: There is a bug preventing the assignment of prices to the secret shop, it'll be fixed later.
Depends on https://github.com/DaftBrit/Archipelago/pull/12

Add spell refreshes and secret shop locations

---

data/archipelago/scripts/ap_spawned_timer_finish.lua
data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/spawn_kill_saver.lua
init.lua

Load key gets set either when you move right for the first time or when you receive items on new game

Fine tuning for when we set the load key

---

data/archipelago/entities/items/ap_trap_item.xml
data/archipelago/scripts/ap_pedestal_replacer.lua
data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/item_mappings.lua
data/archipelago/scripts/item_utils.lua
data/archipelago/scripts/shopitem_utils.lua

Made money sent to other players just auto-added to the wallet.
Fixed it so it doesn't set off a trap when you pick up someone else's trap.
Minor adjustments to pedestal positioning of items

Trap fix, gold auto-get, pedestal item positioning changes

---

data/archipelago/scripts/ap_pedestal_replacer.lua
init.lua

After playing around with it, this rate feels pretty good.

Halving the rate on pedestal replacement

---

data/archipelago/entities/items/orbs/fake_orb.xml
data/archipelago/scripts/ap_extend_ending.lua
data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/constants.lua
data/archipelago/scripts/item_utils.lua
init.lua

I did this while on a short break at work because it was on my mind. Have not tested, intend to test later, just needed to get it out of my head so I can focus.

Fix for pure ending

---

data/archipelago/entities/items/orbs/fake_orb.xml
data/archipelago/scripts/ap_extend_ending.lua
data/archipelago/scripts/constants.lua
data/archipelago/scripts/item_utils.lua
init.lua

Trying and failing to get orbs to redeliver on continue, since the orb count doesn't stay if you didn't pick up the actual orb for some reason that I cannot figure out. Probably something hard coded?
The current issue is when the fake orb spawns, it doesn't like, spawn all the way? It thinks the entity ID is nil for some reason.

Orb shenanigans

---

init.lua

It looks like there's some limit to how much data Noita can process in a single message, so putting in 3+ games (or at least putting in SC2 WoL, Noita, and ArchipIDLE) at the same time makes the DataPackage just plain not get received. This fix makes it so each game is put in one at a time.

Fixed the datapackage issue, I hate this game

---

data/archipelago/scripts/caches.lua
data/archipelago/scripts/seeded_cache.lua
init.lua
settings.lua

GivePlayerOrbsOnSpawn was triggering every time an item was received. Now should only trigger if the index is 0, which means it'll only happen on continue (or the first item). Still trying to get rid of that picked up message altogether if I can.

Fix for picked up blank message

---

data/archipelago/scripts/item_utils.lua
init.lua

Also re-ordered the recv message commands so it's in a more logical order

Reworked datapackage stuff a bit based on feedback

---

data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/item_mappings.lua
data/archipelago/scripts/item_utils.lua
data/archipelago/scripts/items/potion_saver_remover.lua

Stop potions from breaking within 1.5 seconds of spawning.

Potion spawning saver

---

data/archipelago/entities/items/base_ap_shopitem.xml
data/archipelago/scripts/ap_utils.lua
data/archipelago/translations.csv

Fixed the pedestal crash. It still causes the error, but the game won't crash anymore.

Pedestal crash fix

---

data/archipelago/scripts/patches/extend_snowcastle_cavern.lua

Should match the Hiisi Base prices now

Fix for secret shop prices

---

data/archipelago/scripts/ap_utils.lua
init.lua

Shoots out a spell in two directions with a rainbow trail. It's very dumb, but I like it so

Countdown hitting 0 does something now

---

init.lua

This should make it so when the stored index is off and it syncs, it will now set the index to the value it should be.
Also renamed index to stored_index since it was getting confusing.

Fix for index values

---

init.lua
settings.lua

Probably should do this now since the addition to AP should be very soon

Commented out debug items

---

data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/patches/ap_pedestal_replacer.lua

This is what I get for solo testing mostly

Fix for pedestals

---

data/archipelago/scripts/patches/ap_heart_and_chest_replacer.lua
data/entities/animals/ap_chest_leggy.xml

Accidentally made them replace all specially spawned chests instead of none of them as it was intended

Mimic fix so that there aren't tons of mimics in the mines

---

init.lua
settings.lua

Added a setting to let you disable death link if you regretted your decisions.

Death link toggle setting, also slight clean up

---

data/archipelago/scripts/patches/ap_extend_ending.lua

I'm just gonna merge this because like, how in the hell could this even break something. Famous last words, I know

Extra orbs no longer breaks pure ending sending out

---

data/archipelago/scripts/constants.lua
data/archipelago/scripts/item_mappings.lua
data/archipelago/scripts/item_utils.lua
data/archipelago/scripts/items/ap_chest_random.lua
data/archipelago/scripts/patches/ap_heart_and_chest_replacer.lua
data/archipelago/scripts/patches/ap_orb_init_random.lua
data/archipelago/scripts/patches/ap_pedestal_replacer.lua
data/archipelago/scripts/patches/extend_temple_altar.lua
data/archipelago/scripts/shopitem_utils.lua
init.lua

For use with the AP update that will hopefully be 0.4.2 soon.

Support for extra orbs, shop price reduction, and also parallel world support

---

data/archipelago/scripts/caches.lua
data/archipelago/scripts/seeded_cache.lua
init.lua

Support per PR 1933 https://github.com/ArchipelagoMW/Archipelago/pull/1933
That PR is to remove the assertion that different games have to have unique IDs across all games in AP.
So to do this, I've made a new cache where we compare the slot numbers to the game the player is playing.

Better Datapackage Support

---

data/archipelago/scripts/ap_biome_mapping.lua

Added support for the new biome. Extremely minimal update.

Support for the new biome

---

data/archipelago/scripts/item_mappings.lua

Draft PR mostly to keep this in mind for when the main Archipelago is updated

Change so extra life perks are persistent

---

init.lua

Based on this pull request: https://github.com/ArchipelagoMW/Archipelago/pull/2557
And also based on discussion with Vi (Witness maintainer).
Will leave this as a PR until the above mentioned docs PR gets merged.

Change for death link messaging to match the community consensus

---

data/archipelago/scripts/ap_utils.lua
data/archipelago/scripts/apply_ap_patches.lua
data/archipelago/scripts/bosses/ap_kivi_death.lua
data/archipelago/scripts/bosses/ap_kivi_death_swap.lua
data/archipelago/scripts/bosses/ap_meatball_death.lua
data/archipelago/scripts/bosses/ap_tapion_death.lua
data/archipelago/scripts/bosses/ap_tapion_death_swap.lua
data/archipelago/scripts/item_utils.lua

Adds Kivi, the deer, and meatball to the boss check pool.

Add the new bosses

---

bin/note.txt
init.lua

Update to v0.26.6-10 of the AP lua client lib.
The only change I'm really caring about here is that games can have overlapping item IDs and location IDs now, so I updated the couple things that cared about that.

Update client lib

---

init.lua
settings.lua

It feels a little hacky with the magic numbers but ehhhh

Change death link to have 3 options
